
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package sintatico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 7;
  public static final int For = 8;
  public static final int Numero = 29;
  public static final int Operador_Booleano = 20;
  public static final int ERROR = 30;
  public static final int Tipo_Dado = 15;
  public static final int Fecha_Chaves = 26;
  public static final int Fecha_Parenteses = 24;
  public static final int Identificador = 28;
  public static final int Int = 5;
  public static final int Operador_Aritmetico = 21;
  public static final int Operador_Atribuicao = 18;
  public static final int Operador_Relacional = 17;
  public static final int Abre_Chaves = 25;
  public static final int Operador_Logico = 16;
  public static final int Main = 12;
  public static final int Ponto_Virgula = 27;
  public static final int EOF = 0;
  public static final int Operador_Incremento = 19;
  public static final int If = 6;
  public static final int Linha = 22;
  public static final int error = 1;
  public static final int Aspas = 3;
  public static final int Do = 13;
  public static final int Void = 11;
  public static final int Igual = 2;
  public static final int Public = 9;
  public static final int Static = 10;
  public static final int While = 14;
  public static final int Abre_Parenteses = 23;
  public static final int String = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Igual",
  "Aspas",
  "String",
  "Int",
  "If",
  "Else",
  "For",
  "Public",
  "Static",
  "Void",
  "Main",
  "Do",
  "While",
  "Tipo_Dado",
  "Operador_Logico",
  "Operador_Relacional",
  "Operador_Atribuicao",
  "Operador_Incremento",
  "Operador_Booleano",
  "Operador_Aritmetico",
  "Linha",
  "Abre_Parenteses",
  "Fecha_Parenteses",
  "Abre_Chaves",
  "Fecha_Chaves",
  "Ponto_Virgula",
  "Identificador",
  "Numero",
  "ERROR"
  };
}

